function propertyCard(p){const sale=p.status==='Venda';return `<article class="card clickable-card" tabindex="0" role="link" data-detail="${p.id}"><div class="card-media" style="background-image:url('imagens/${p.image}')"><span class="tag ${sale?'sale':''}">${sale?'À VENDA':'PARA ALUGAR'}</span><span class="price">${p.price}</span></div><div class="card-body"><h3>${p.title}</h3><p class="address">⌖ ${p.address}</p><div class="features"><span>🛏 ${p.beds} Quartos</span><span>🚿 ${p.baths} Banheiros</span><span>🚗 ${p.parking} Vaga${p.parking>1?'s':''}</span><span>▣ ${p.area}</span></div>${sale&&p.finance?'<div class="finance">🏦 Aceita financiamento</div>':''}<div class="agent">👨‍💼 Corretor: Moises Oliveira</div><div class="details-hint">Ver detalhes →</div></div></article>`}
function fillCards(id,props){const el=document.getElementById(id);if(el)el.innerHTML=props.map(propertyCard).join('')}
if(typeof NAYHOUSE!=='undefined'){fillCards('rentals',NAYHOUSE.properties.filter(p=>p.status==='Aluguel'));fillCards('sales',NAYHOUSE.properties.filter(p=>p.status==='Venda'))}
document.addEventListener('click',e=>{const c=e.target.closest('[data-detail]');if(c?.dataset.detail)location.href='imovel.html?id='+encodeURIComponent(c.dataset.detail)})
document.addEventListener('keydown',e=>{const el=document.activeElement;if(el?.dataset?.detail&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.href='imovel.html?id='+encodeURIComponent(el.dataset.detail)}})
function moveCarousel(track,dir){if(!track)return;const cards=[...track.querySelectorAll('.card')];if(!cards.length)return;let i=0,d=Infinity;cards.forEach((c,n)=>{const x=Math.abs(c.offsetLeft-track.scrollLeft);if(x<d){d=x;i=n}});i=Math.max(0,Math.min(cards.length-1,i+dir));track.scrollTo({left:cards[i].offsetLeft,behavior:'smooth'})}
document.querySelectorAll('.carousel-btn').forEach(b=>b.addEventListener('click',()=>moveCarousel(document.getElementById(b.dataset.carousel),b.classList.contains('next')?1:-1)))
const mt=document.querySelector('.menu-toggle');if(mt)mt.addEventListener('click',()=>{const n=document.querySelector('.nav');if(n){n.classList.toggle('open');mt.setAttribute('aria-expanded',n.classList.contains('open'))}})
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav')?.classList.remove('open')))
document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear())
